name:                refinery
version:             0.3.0.0
github:              "totbwf/refinery"
license:             BSD3
author:              "Reed Mullanix"
maintainer:          "reedmullanix@gmail.com"
copyright:           "2019 Reed Mullanix"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Toolkit for building proof automation systems
category: Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/refinery#readme>

dependencies:
- base >= 4.7 && < 5
- exceptions >= 0.10
- mmorph >= 1
- mtl >= 2

ghc-options:
  - -Wall
  - -Wredundant-constraints

library:
  source-dirs: src

tests:
  refinery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refinery
    - hspec
    - checkers
    - QuickCheck
