name:                refinery
version:             0.1.0.0
github:              "githubuser/refinery"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/refinery#readme>

extra-source-files: examples/*.hs

dependencies:
- base >= 4.7 && < 5
- mtl >= 2 && < 3
- containers >= 0.5 && < 0.6
- unbound-generics >= 0.3 && < 0.4
- template-haskell >= 2.13 && < 2.14

library:
  source-dirs: src

tests:
  refinery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refinery
